### ISSUE TITLE
完全没有速度，求教如何用自己找的代理，或者能用gae、蓝灯、xxnet之类吗？

### ISSUE THREAD

**Issue by tomcat-bj** [hanbang-wang/Yun-Brute#10]
跑了好几天了，一直这样
2017/07/04 11:06:49 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:06:54 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:06:59 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:07:05 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:07:10 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:07:15 Get https://free-proxy-list.net/: dial tcp 93.46.8.89:443: connectex: The semaph
ore timeout period has expired.
2017/07/04 11:07:15 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:07:21 Get https://www.sslproxies.org/: x509: certificate signed by unknown authority
2017/07/04 11:07:24 Terminating program, current progress: 0000

**Comment by superfashi** [comment]
代理问题，开vpn获取代理就好了。

_Sent from my Samsung SM-G9500 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tomcat-bj** [comment]
感谢！
我现在开了xxnet，设置全局使用gae代理，没有效果，不能使用这个方式吗？
请问一下使用vpn的话，需要做什么设置吗？

**Comment by tomcat-bj** [comment]
尝试了vpn，得到这个提示，不知正常吗？目前还是0/s
2017/07/04 14:15:33 Get http://proxy.tekbreak.com/1000/json: read tcp 10.211.1.82:26752->188.121.46.1:80: wsarecv: An existing connection was for
cibly closed by the remote host.
2017/07/04 14:15:40 Get http://proxy.tekbreak.com/1000/json: read tcp 10.211.1.82:27757->188.121.46.1:80: wsarecv: An existing connection was for
cibly closed by the remote host.
2017/07/04 14:15:45 No proxies left! Threads will hang up...d15h50m18s
2017/07/04 14:15:47 Get http://proxy.tekbreak.com/1000/json: read tcp 10.211.1.82:27815->188.121.46.1:80: wsarecv: An existing connection was for
cibly closed by the remote host.
2017/07/04 14:15:48 No proxies left! Threads will hang up...
2017/07/04 14:15:50 No proxies left! Threads will hang up...71d7h7m22s
2017/07/04 14:15:52 No proxies left! Threads will hang up...
2017/07/04 14:15:52 No proxies left! Threads will hang up...
2017/07/04 14:15:55 Get http://proxy.tekbreak.com/1000/json: read tcp 10.211.1.82:28082->188.121.46.1:80: wsarecv: An existing connection was for
cibly closed by the remote host.
2017/07/04 14:15:55 No proxies left! Threads will hang up...
2017/07/04 14:15:57 No proxies left! Threads will hang up...
2017/07/04 14:16:00 No proxies left! Threads will hang up...
2017/07/04 14:16:02 Get http://proxy.tekbreak.com/1000/json: read tcp 10.211.1.82:28875->188.121.46.1:80: wsarecv: An existing connection was for
cibly closed by the remote host.
2017/07/04 14:16:02 No proxies left! Threads will hang up...
2017/07/04 14:16:03 No proxies left! Threads will hang up...
2017/07/04 14:16:03 No proxies left! Threads will hang up...
2017/07/04 14:16:03 No proxies left! Threads will hang up...
2017/07/04 14:16:03 No proxies left! Threads will hang up...
2017/07/04 14:16:05 No proxies left! Threads will hang up...
2017/07/04 14:16:19 No proxies left! Threads will hang up...d20h23m13s
2017/07/04 14:16:28 Get http://proxy.tekbreak.com/1000/json: dial tcp 188.121.46.1:80: connectex: A connection attempt failed because the connect
ed party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2017/07/04 14:16:30 No proxies left! Threads will hang up...
2017/07/04 14:16:31 No proxies left! Threads will hang up...2d4h16m31s
2017/07/04 14:16:33 No proxies left! Threads will hang up...6d2h31m26s

**Comment by tomcat-bj** [comment]
现在换了个网址，情况还是很不好
2017/07/04 15:03:10 Get https://free-proxy-list.net/: dial tcp 93.46.8.89:443: connectex: No connection could be made because the target machine
actively refused it.
2017/07/04 15:03:19 Get https://free-proxy-list.net/: dial tcp 93.46.8.89:443: connectex: No connection could be made because the target machine
actively refused it.
2017/07/04 15:03:20 No proxies left! Threads will hang up...
2017/07/04 15:03:30 No proxies left! Threads will hang up...
2017/07/04 15:03:32 No proxies left! Threads will hang up...
2017/07/04 15:03:33 No proxies left! Threads will hang up...

**Comment by superfashi** [comment]
就是没代理，不是只换个网址就好的
你要可以的话自己存个代理文件然后自己写Proxier
```Go
updater = append(updater,
		&Proxies{
			func() {
				// 读取文件……
				addProxy(Proxy{代理类型（http，https）, ip, 端口})
			},
		})
```

**Comment by tomcat-bj** [comment]
看了一下	updater = append(updater,		&Proxies{
好像有戏，就是从没用过go语言，不知读取文件改用哪句？
我自己维护个goodip.txt
格式为：
http,216.58.200.40,125
https,127.0.0.1,8087
这样可以吗？
最后一句用来实现调用我自己搭建的GAE代理

试着直接添加这段执行，
	updater = append(updater,
		&Proxies{
			func() {
						addProxy(Proxy{"http", 127.0.0.1, 8087})
			},
		})
结果报错如下：.\brute.go:131: syntax error: unexpected literal .0, expecting comma or }

**Comment by superfashi** [comment]
127.0.0.1是字符串，打引号。
你这样格式的代理，按行读取，按逗号分隔就好了。

_Sent from my Samsung SM-G9500 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tomcat-bj** [comment]
成功！爽！瞬间70+/s，然后…… x509，看来有门，再研究研究就可以飞速破解啦！感谢！
