### ISSUE TITLE
真是不好意思，又来麻烦您，我找了个json格式和您以前的完全不同，解析失败了

### ISSUE THREAD

**Issue by tomcat-bj** [hanbang-wang/Yun-Brute#11]
临时抱佛脚研究go语言实在是迷糊，可以麻烦您不忙的时候针对这个格式写一下append(updater)里面var sca []struct{} 的相关代码吗？
{"code": 0, "msg": "", "data": { "count": 10,"proxy_list": [ "119.23.129.24:3128", "121.40.108.76:80", "220.249.185.178:9999", "222.95.17.85:808", "110.73.8.157:8123", "117.78.51.231:3128", "218.20.218.144:808", "123.139.56.238:9999", "182.88.27.170:8123", "218.15.25.153:808" ]}}

本来想转成txt格式来做成适用free2016.txt那段代码的txtx，可是xicidaili那个txt文件怎么都获取不到，也不知道该是什么格式，只好又来求助您啦

**Comment by superfashi** [comment]
新建个struct：
```
type Proxies struct {
	Code int `json:"code"`
	Msg string `json:"msg"`
	Data struct {
		Count int `json:"count"`
		ProxyList []string `json:"proxy_list"`
	} `json:"data"`
}
```
然后用`json.Unmarshall`把`.Body`塞到这个struct的实例里，读取`.Data.ProxyList`里的每一个字符串，分割一下，再`addProxy`。
就不给你详细写代码了，还有这种非Bug问题就不要在这里问了。
