### ISSUE TITLE
今天百度云换地址了，项目不能用了

### ISSUE THREAD

**Issue by tomcat-bj** [hanbang-wang/Yun-Brute#13]
前几天用短链已经失效，手动访问转换为长链还可以用，现在长链格式不再是https://pan.baidu.com/share/init?shareid=11203993113&uk=1232132213 这样的了

这是短链：
H:\Yun-Brute>go run pan.go https://pan.baidu.com/s/1pLPucmn
2017/09/07 10:34:42 Unexpected error: http://pan.baidu.com/s/1pLPucmnhttps://pan.baidu.com/s/1pLPucmn
exit status 1

这是手动访问转换后的长链
H:\Yun-Brute>go run pan.go https://pan.baidu.com/share/init?surl=pLPucmn
2017/09/07 10:34:53 No proper resolver found!
exit status 1

H:\Yun-Brute>go run pan.go "https://pan.baidu.com/share/init?surl=pLPucmn"
2017/09/07 10:36:50 No proper resolver found!
exit status 1

**Comment by superfashi** [comment]
试试吧
