### ISSUE TITLE
43ssignal: killed

### ISSUE THREAD

**Issue by yongbeima** [hanbang-wang/Yun-Brute#14]
请问下这是什么错误：
]go run brute.go https://pan.baidu.com/share/***************
2017/09/27 12:53:23 Unknown error! Server returned 500! 41/s 10h54m51s
[==>------------------------------------------]   5.01% 33/s 13h19m43ssignal: killed

谢谢

**Comment by yongbeima** [comment]
请教下这个又是什么错误
go run brute.go https://pan.baidu.com/share/***************
2017/09/27 16:11:25 Unknown error! Service returned 1 with message: ""
2017/09/27 16:11:25 Unknown error! Service returned 1 with message: ""
2017/09/27 16:11:25 Unknown error! Service returned 1 with message: ""
2017/09/27 16:11:25 Unknown error! Service returned 1 with message: ""
2017/09/27 16:11:26 Unknown error! Service returned 1 with message: ""
2017/09/27 16:11:30 Terminating program, current progress: 00ouh53m14s^C
exit status 1

谢谢

**Comment by yongbeima** [comment]
好像是memory问题，
cat /var/log/messages
Sep 27 13:20:50 galowma kernel: Out of memory: Kill process 1363 (brute) score 635 or sacrifice child

跑久了内存确实会上来
麻烦大大修复下bug

谢谢

**Comment by superfashi** [comment]
内存小的话把线程设置少一点

**Comment by yongbeima** [comment]
默认是多少线程？

**Comment by yongbeima** [comment]
看了下资源监测，内存使用率还是随着时间推移往上飘，怀疑是哪里内存回收没做好。

**Comment by yongbeima** [comment]
我内存1G，线程设成600，试了一下确实破解了密码。
多谢！
不过程序跑的过程中内存使用率确实不断上升，最后大概在50%内存使用率稳住了。
