### ISSUE TITLE
No proper resolver found!

### ISSUE THREAD

**Issue by solarhell** [hanbang-wang/Yun-Brute#5]
⋊> ~/Yun-Brute on master ◦ go run brute.go https://pan.baidu.com/share/init?shareid=532812994&uk=3322228950
[1] 55803
⋊> ~/Yun-Brute on master ◦ go run brute.go 2016/11/10 21:15:13 No proper resolver found!
exit status 1

[1]+  Exit 1

**Comment by superfashi** [comment]
这是因为链接有特殊字符。

``` bash
go run brute.go "https://pan.baidu.com/share/init?shareid=532812994&uk=3322228950"
```

用引号引起来就好了。
