### ISSUE TITLE
Always responding Unknown error! Service returned 1 with message: ""

### ISSUE THREAD

**Issue by kotori2** [hanbang-wang/Yun-Brute#7]
虽说看起来不影响，但是这会不会导致大量密码没有测试到呢？

**Comment by superfashi** [comment]
不会，你可以看[这里](https://github.com/hanbang-wang/Yun-Brute/blob/master/brute.go#L350-L376)的逻辑：  
只有在 362 行成功的时候才会 `break`。  
而且不一定是同一个线程提出的警告，所以不用担心。
