### ISSUE TITLE
曾经使用win预编译版成功跑出，但是没法在我的win2003翔云主机运行，前天装了go环境，跑go run brute.go出问题了

### ISSUE THREAD

**Issue by tomcat-bj** [hanbang-wang/Yun-Brute#8]
跑了一晚上，早上来看这个结果……请问这是什么情况呢？

goroutine 6667510 [select]:
net/http.setRequestCancel.func3(0x0, 0x19ecfda0, 0x13548750, 0x152cae9c, 0x1c5de
500)
H:/Go/src/net/http/client.go:320 +0x12a
created by net/http.setRequestCancel
H:/Go/src/net/http/client.go:330 +0x236

goroutine 6667511 [runnable, locked to thread]:
syscall.Syscall(0x71b6410c, 0x3, 0x2, 0x1, 0x0, 0x2ace4780, 0x313b0000, 0x0)
H:/Go/src/runtime/syscall_windows.go:163 +0x51
syscall.socket(0x2, 0x1, 0x0, 0x44e04e, 0x850450, 0x1)
H:/Go/src/syscall/zsyscall_windows.go:1407 +0x53
syscall.Socket(0x2, 0x1, 0x0, 0x270f, 0x3, 0x6d390f)
H:/Go/src/syscall/syscall_windows.go:705 +0x45
net.sysSocket(0x2, 0x1, 0x0, 0x10, 0x502b7c, 0x152caf80)
H:/Go/src/net/sock_windows.go:21 +0x48
net.socket(0x8146c0, 0x113ee0f0, 0x6d390f, 0x3, 0x2, 0x1, 0x0, 0x0, 0x815a00, 0x
0, …)
H:/Go/src/net/sock_posix.go:41 +0x35
net.internetSocket(0x8146c0, 0x113ee0f0, 0x6d390f, 0x3, 0x815a00, 0x0, 0x815a00,
0x1ac1ebe0, 0x1, 0x0, …)
H:/Go/src/net/ipsock_posix.go:154 +0xfa
net.doDialTCP(0x8146c0, 0x113ee0f0, 0x6d390f, 0x3, 0x0, 0x1ac1ebe0, 0x8502ec, 0x
2fd79b70, 0x8502ec)
H:/Go/src/net/tcpsock_posix.go:62 +0x7d
net.dialTCP(0x8146c0, 0x113ee0f0, 0x6d390f, 0x3, 0x0, 0x1ac1ebe0, 0x7ffe0014, 0x
423f7f, 0x7ffe0014)
H:/Go/src/net/tcpsock_posix.go:58 +0xa6
net.dialSingle(0x8146c0, 0x113ee0f0, 0x1c6803c0, 0x813630, 0x1ac1ebe0, 0x0, 0x0,
0x0, 0x0)
H:/Go/src/net/dial.go:521 +0x347
net.dialSerial(0x8146c0, 0x113ee0f0, 0x1c6803c0, 0x1266b928, 0x1, 0x1, 0x0, 0x0,
0x0, 0x0)
H:/Go/src/net/dial.go:489 +0x1ef
net.(*Dialer).DialContext(0x83ef80, 0x8146c0, 0x113ee0f0, 0x6d390f, 0x3, 0x1ac1e
bc0, 0x13, 0x0, 0x0, 0x0, …)
H:/Go/src/net/dial.go:371 +0x60e
net/http.(*Transport).dial(0x2104e8c0, 0x8146c0, 0x113ee0f0, 0x6d390f, 0x3, 0x1a
c1ebc0, 0x13, 0x0, 0x0, 0x0, …)
H:/Go/src/net/http/transport.go:858 +0x125
net/http.(*Transport).dialConn(0x2104e8c0, 0x8146c0, 0x113ee0f0, 0x1c5de300, 0x1
c6802d0, 0x5, 0x1ac1e0e0, 0x11, 0x0, 0x0, …)
H:/Go/src/net/http/transport.go:1008 +0x174a
net/http.(*Transport).getConn.func4(0x2104e8c0, 0x8146c0, 0x113ee0f0, 0x1ac1e100
, 0x1c5de580)
H:/Go/src/net/http/transport.go:908 +0x3e
created by net/http.(*Transport).getConn
H:/Go/src/net/http/transport.go:910 +0x2b0

goroutine 6667512 [select]:
net.(*netFD).connect.func2(0x8146c0, 0x113ee0f0, 0x28d19b30, 0x1c5dec80)
H:/Go/src/net/fd_windows.go:376 +0x10e
created by net.(*netFD).connect
H:/Go/src/net/fd_windows.go:384 +0x1a3
exit status 2

**Comment by superfashi** [comment]
你这个拷贝全了吗？似乎找不到有用的信息……
也有可能是系统问题……

**Comment by tomcat-bj** [comment]
没全，我把缓存区设到9999，几乎都是类似的信息，担心贴上来文字太多，所以只是贴了最后的一段，我试试看能不能把全部都放上来

**Comment by tomcat-bj** [comment]
正在努力上传全部的记录，能否请您编译一个i386/i686平台上win2003系统下可执行的版本呢？
cpu显示为xeon e5-2650

**Comment by tomcat-bj** [comment]
文件为zip格式，提示类型错误不让传，只好改一下扩展名啦
![1](https://cloud.githubusercontent.com/assets/23627776/25367495/8f8fdb2c-29a8-11e7-8149-2d2bc95991e0.jpg)

**Comment by superfashi** [comment]
看了一眼，可能是你进程太多了，系统有限制。
编译了386的版本，你试试吧。

**Comment by tomcat-bj** [comment]
感谢，已经放在服务器上跑了，明早看结果

**Comment by tomcat-bj** [comment]
……这回的报错变这样了
goroutine 11141363 [runnable]:
net/http.setRequestCancel.func3(0x0, 0x5cf39c80, 0x13edde30, 0x1d6c7b50, 0x5cf51f00)
        C:/Go/src/net/http/client.go:319
created by net/http.setRequestCancel
        C:/Go/src/net/http/client.go:330 +0x236

goroutine 11141364 [runnable, locked to thread]:
syscall.Syscall(0x71b6438d, 0x3, 0x78bac, 0x5cf39ec8, 0x10, 0x313404a0, 0x0, 0x4)
        C:/Go/src/runtime/syscall_windows.go:163 +0x51
syscall.bind(0x78bac, 0x5cf39ec8, 0x10, 0x0, 0x0)
        C:/Go/src/syscall/zsyscall_windows.go:1444 +0x53
syscall.Bind(0x78bac, 0x810130, 0x5cf39ec0, 0x0, 0x0)
        C:/Go/src/syscall/syscall_windows.go:718 +0x59
net.(*netFD).connect(0x5cf53770, 0x8126a0, 0x11332180, 0x0, 0x0, 0x810130, 0x5cf39ea0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:362 +0x528
net.(*netFD).dial(0x5cf53770, 0x8126a0, 0x11332180, 0x8139e0, 0x0, 0x8139e0, 0x5cf39e80, 0x0, 0x1)
        C:/Go/src/net/sock_posix.go:140 +0xa0
net.socket(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x2, 0x1, 0x0, 0x0, 0x8139e0, 0x0, ...)
        C:/Go/src/net/sock_posix.go:92 +0x11a
net.internetSocket(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x8139e0, 0x0, 0x8139e0, 0x5cf39e80, 0x1, 0x
0, ...)
        C:/Go/src/net/ipsock_posix.go:154 +0xfa
net.doDialTCP(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x0, 0x5cf39e80, 0x84bbac, 0x5cfabb70, 0x84bbac)
        C:/Go/src/net/tcpsock_posix.go:62 +0x7d
net.dialTCP(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x0, 0x5cf39e80, 0x7ffe0014, 0x423f6f, 0x7ffe0014)
        C:/Go/src/net/tcpsock_posix.go:58 +0xa6
net.dialSingle(0x8126a0, 0x11332180, 0x5cf22c80, 0x811610, 0x5cf39e80, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:521 +0x347
net.dialSerial(0x8126a0, 0x11332180, 0x5cf22c80, 0x1556a808, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:489 +0x1ef
net.(*Dialer).DialContext(0x83a840, 0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x5cf39e60, 0x13, 0x0, 0x0,
 0x0, ...)
        C:/Go/src/net/dial.go:371 +0x60e
net/http.(*Transport).dial(0x5cf34dc0, 0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x5cf39e60, 0x13, 0x0, 0
x0, 0x0, ...)
        C:/Go/src/net/http/transport.go:858 +0x125
net/http.(*Transport).dialConn(0x5cf34dc0, 0x8126a0, 0x11332180, 0x5cf51e40, 0x5cf22be0, 0x5, 0x5cf3
9d40, 0x11, 0x0, 0x0, ...)
        C:/Go/src/net/http/transport.go:1008 +0x174a
net/http.(*Transport).getConn.func4(0x5cf34dc0, 0x8126a0, 0x11332180, 0x5cf39d60, 0x5cf51f80)
        C:/Go/src/net/http/transport.go:908 +0x3e
created by net/http.(*Transport).getConn
        C:/Go/src/net/http/transport.go:910 +0x2b0

goroutine 11141352 [runnable]:
net/http.setRequestCancel.func3(0x0, 0x5cf47d00, 0x140c50e0, 0x1d62d160, 0x5cf61800)
        C:/Go/src/net/http/client.go:319
created by net/http.setRequestCancel
        C:/Go/src/net/http/client.go:330 +0x236

goroutine 11141377 [runnable]:
net/http.setRequestCancel.func3(0x0, 0x5cf43060, 0x1669c780, 0x1d6247ac, 0x5cf0b7c0)
        C:/Go/src/net/http/client.go:319
created by net/http.setRequestCancel
        C:/Go/src/net/http/client.go:330 +0x236

goroutine 11141378 [runnable, locked to thread]:
syscall.Syscall(0x71b6410c, 0x3, 0x2, 0x1, 0x0, 0x0, 0x31340000, 0x0)
        C:/Go/src/runtime/syscall_windows.go:163 +0x51
syscall.socket(0x2, 0x1, 0x0, 0x44dfde, 0x84bd10, 0x1)
        C:/Go/src/syscall/zsyscall_windows.go:1407 +0x53
syscall.Socket(0x2, 0x1, 0x0, 0x328, 0x3, 0x1562bb80)
        C:/Go/src/syscall/syscall_windows.go:705 +0x45
net.sysSocket(0x2, 0x1, 0x0, 0x10, 0x502bac, 0x1d624b00)
        C:/Go/src/net/sock_windows.go:21 +0x48
net.socket(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x2, 0x1, 0x0, 0x0, 0x8139e0, 0x0, ...)
        C:/Go/src/net/sock_posix.go:41 +0x35
net.internetSocket(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x8139e0, 0x0, 0x8139e0, 0x5cf43220, 0x1, 0x
0, ...)
        C:/Go/src/net/ipsock_posix.go:154 +0xfa
net.doDialTCP(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x0, 0x5cf43220, 0x84bbac, 0x5cfb1b70, 0x84bbac)
        C:/Go/src/net/tcpsock_posix.go:62 +0x7d
net.dialTCP(0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x0, 0x5cf43220, 0x7ffe0014, 0x423f6f, 0x7ffe0014)
        C:/Go/src/net/tcpsock_posix.go:58 +0xa6
net.dialSingle(0x8126a0, 0x11332180, 0x5cf08b40, 0x811610, 0x5cf43220, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:521 +0x347
net.dialSerial(0x8126a0, 0x11332180, 0x5cf08b40, 0x1562bb80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/net/dial.go:489 +0x1ef
net.(*Dialer).DialContext(0x83a840, 0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x1d624aa0, 0x10, 0x0, 0x0,
 0x0, ...)
        C:/Go/src/net/dial.go:371 +0x60e
net/http.(*Transport).dial(0x5cf10d20, 0x8126a0, 0x11332180, 0x6d222f, 0x3, 0x1d624aa0, 0x10, 0x0, 0
x0, 0x0, ...)
        C:/Go/src/net/http/transport.go:858 +0x125
net/http.(*Transport).dialConn(0x5cf10d20, 0x8126a0, 0x11332180, 0x5cf0b700, 0x5cf08aa0, 0x5, 0x5cf4
3100, 0x11, 0x0, 0x0, ...)
        C:/Go/src/net/http/transport.go:1008 +0x174a
net/http.(*Transport).getConn.func4(0x5cf10d20, 0x8126a0, 0x11332180, 0x5cf43120, 0x5cf0b840)
        C:/Go/src/net/http/transport.go:908 +0x3e
created by net/http.(*Transport).getConn
        C:/Go/src/net/http/transport.go:910 +0x2b0

runtime stack:
runtime.throw(0x6d515d, 0xd)
        C:/Go/src/runtime/panic.go:596 +0x7c
runtime.(*mcache).refill(0x313406f0, 0x10, 0xb63a20f)
        C:/Go/src/runtime/mcache.go:124 +0xe3
runtime.(*mcache).nextFree.func1()
        C:/Go/src/runtime/malloc.go:526 +0x28
runtime.systemstack(0x6f37feb0)
        C:/Go/src/runtime/asm_386.s:353 +0x88
runtime.(*mcache).nextFree(0x313406f0, 0x10, 0x6f37ff2c, 0x7c95e5d8, 0x7c95e5e0)
        C:/Go/src/runtime/malloc.go:527 +0x9e
runtime.mallocgc(0xf0, 0x6cad00, 0x7c958001, 0x5ce2b520)
        C:/Go/src/runtime/malloc.go:679 +0x642
runtime.newobject(0x6cad00, 0x7c821f5f)
        C:/Go/src/runtime/malloc.go:808 +0x2c
runtime.malg(0x800, 0x0)
        C:/Go/src/runtime/proc.go:2821 +0x27
runtime.newproc1(0x6e65fc, 0x401819c0, 0x14, 0x0, 0x62f6a0, 0x5cf5def0)
        C:/Go/src/runtime/proc.go:2875 +0x48c
runtime.newproc.func1()
        C:/Go/src/runtime/proc.go:2845 +0x41
runtime.systemstack(0x11342000)
        C:/Go/src/runtime/asm_386.s:337 +0x5e
runtime.mstart()
        C:/Go/src/runtime/proc.go:1132

**Comment by superfashi** [comment]
一样的，就是线程问题。你开了多少线程？

**Comment by tomcat-bj** [comment]
没有设置t参数，用的默认，发现好像和运行时长有关，之前基本都是第二天检查的时候挂掉
我测试跑一段时间就中断，使用p参数继续跑，今天上午又一次接力跑后，用go的方式终于跑出来一个。

**Comment by superfashi** [comment]
你试着换个系统吧orz

**Comment by tomcat-bj** [comment]
T_T 服务器，怀疑和云主机虚拟出的硬件有关
还有个centos服务器，生产环境，配置还比较低，不敢随便挂
