### ISSUE TITLE
速度慢 (Very slow cracking speed)

### ISSUE THREAD

**Issue by lewisxy** [hanbang-wang/Yun-Brute#9]
破解速度只有不到30/s，并不像展示的那样每秒一百多，这样的要花费近一天时间
Unlike the demonstration you showed, the cracking speed is merely less than 30/s which would take about a day.

**Comment by superfashi** [comment]
可不止一天时间哦（笑
想要速度快，自己找http/s代理就好了。

**Comment by lewisxy** [comment]
@hanbang-wang 我用的是100Mbps光纤，而且在多台电脑上进行过测试，最快的也超不过40/s，难道http(s)代理能够加速（如果真是这样的话能解释一下吗）？另外那个`-t`的线程参数好像没有什么用，我虽然不知道你那个默认是多少，但是我调成1000或10000真是速度并没有任何区别，不知道是什么问题，另外如果这个支持分布式破解就好了，现在想分布式只能手动调`-p`参数，不太方便。不过还是要感谢你，经过4个多小时跑出来了。

**Comment by tomcat-bj** [comment]
羡慕30/s的，我这用过机房、多个地域的adsl，最多18/s，这两天阿里机房的服务器一直0/s，北京adsl只有2/s
